# Generated by Django 4.1.7 on 2023-04-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='name',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
